# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'
matrix:
 include:
   - os: osx
     r: release
   - os: osx
     r: devel
   - os: linux
     r: release
   - os: linux
     r: devel
