# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

# Use Ubuntu 14.04 Trusty support for better C++11 support
sudo: required
dist: trusty

language: R
sudo: true
cache: packages
warnings_are_errors: false

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'
matrix:
 include:
   - os: linux
     r: release
   - os: linux
     r: devel
   - os: osx
     r: release
   - os: osx
     r: devel
